all:
	g++  -o InterruptTest InterruptTest.cpp -lwiringPi
	g++  -o SwitchTest SwitchTest.cpp -pthread
	g++  -o PreemptTest PreemptTest.cpp -pthread
clean:
	rm InterruptTest
	rm SwitchTest
	rm PreemptTest
